spring:
  application:
    name: Internet_Shop_Backend
  profiles:
    active: h2
  mail:
    host: smtp.gmail.com
    port: 587
    username: alykulovalydin@gmail.com
    password: xjxsxffzogqbnciq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}

jwt:
    secret: afsdkhjasdjhkfhadsjklghadslkjghaskdjghakjsd
    expiration: 1800000
